### PR TITLE
Fix build with GCC10

### LINKED ISSUE #196: Won't build with all compilers
mailio fails to build with at least clang 18.1
with:
`error: no member named 'str' in 'std::basic_ostream<char>'`

The cause is quoted_printable.cpp, line 45:

`const string QMARK_HEX = EQUAL_STR + (std::stringstream() << std::hex << static_cast<int>(QUESTION_MARK_CHAR)).str();`

This works depending on the stdcpp implementation.

I assume, that (std::stringstream() << ...) devolves into an ostring (return value of "operator<<"), which does not have a member str().

Changing this to
```
std::stringstream strstream;
strstream << std::hex << static_cast<int>(QUESTION_MARK_CHAR)
const string QMARK_HEX = EQUAL_STR + strstream.str();
```

should fix that. I don't know if there are more errors, yet.

### PR DESCRIPTION
**Pull request by ssauermann**
Fixes #196

### CODE REVIEW

**Comment by karastojko** [comment]
Thanks a lot.
