### ISSUE TITLE
Won't build with all compilers

### ISSUE THREAD

**Issue by stitch3210** [karastojko/mailio#196]
mailio fails to build with at least clang 18.1
with:
`error: no member named 'str' in 'std::basic_ostream<char>'`

The cause is quoted_printable.cpp, line 45:

`const string QMARK_HEX = EQUAL_STR + (std::stringstream() << std::hex << static_cast<int>(QUESTION_MARK_CHAR)).str();`

This works depending on the stdcpp implementation.

I assume, that (std::stringstream() << ...) devolves into an ostring (return value of "operator<<"), which does not have a member str().

Changing this to
```
std::stringstream strstream;
strstream << std::hex << static_cast<int>(QUESTION_MARK_CHAR)
const string QMARK_HEX = EQUAL_STR + strstream.str();
```

should fix that. I don't know if there are more errors, yet.

**Comment by stitch3210** [comment]
Update: 
The library makes the difference.
It builds with libstdc++, fails with libc++.

**Comment by Spixmaster** [comment]
You mention two compilers. Does the error `no member named 'str'` appear in GCC v10 and Clang v18? So was the compiler bug in both of them? Or does your fix not build with GCC v10?

In general, I do not see the value in adding a fix to adhere to broken compiler version.

**Comment by stitch3210** [comment]
I want to clarify: the compiler is **not broken**, it behaves correctly according to the c++ standard at the time.
I turns out, the error occurs when using gccv10 or with clang when using gcc's libraries. It may affect other compilers, that we don't use, I can't say.

There was a slight change to the standard a few years back, aimed at improving usability of operator<<, which was then incorporated into the lib headers at and after 2020.
See here: https://cplusplus.github.io/LWG/issue1203

We, like many others, build on slightly older toolchains, to achieve better binary compatibility with existing systems, as is common practice, when building binaries for distribution.

I would generally agree with you, but considering the triviality of the fix and the fact, that it has no side-effects either functionality- or performance-wise, it would be a cheap win to fix it and make mailio work with slightly outdated compilers, which are still in use.

**Comment by Spixmaster** [comment]
Which Clang versions are affected?

**Comment by stitch3210** [comment]
It's not the compiler, so it is independent of the clang version.
It's the library - in this case libstdc++, which is shipped with gcc10.
Whenever that or an older one is used, no matter the compiler, the error will occur.
In our case, for example, one of the failing builds is when cross-compiling for aarch64 with the sysroot taken from ubuntu 20.04.

Currently we're working around that by patching mailio.
